site_name: Willkommen bei aula!
site_url: https://docs.aula.de
site_author: Leonard Haas
site_description: Documentation for aula 2025

theme:
  logo: assets/logo.png
  favicon: assets/logo.png
  name: material 
  language: de 

  palette:
    - scheme: slate
      toggle:
          icon: material/lightbulb-outline
          name: Switch to light mode
      primary: custom
      accent:  custom
    - scheme: default
      toggle:
          icon: material/lightbulb
          name: Switch to dark mode
      primary: custom
      accent: custom

  font:
    text: Roboto

  features:
    - navigation.tracking
    - navigation.sections
    - navigation.instant
    - toc.integrate
    - navigation.path
    - navigation.top
    - search-suggest
    - search-highlight

extra:
  cname: docs.aula.de
 

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.magiclink
  - pymdownx.blocks.caption

copyright: Copyright &copy; 2025 aula gGmbH

nav:
  - loslegen.md
  - erste_hilfe.md
  - benutzerverwaltung.md
  - profil.md
  - raeume.md
  - phasen.md
  - ideen_menu.md
  - boxen_menu.md
  - Administrationsbereich.md
  - Konfigurationen.md


extra_css:
  - stylesheets/extra.css